# Generated by Django 5.2 on 2025-10-24 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreport',
            name='price',
        ),
        migrations.RemoveField(
            model_name='salesreport',
            name='quantity_sold',
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
        ),
    ]
